name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version.outputs.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate image version tag
        id: version
        run: |
          VERSION=$(date +%Y%m%d)-${GITHUB_SHA::8}
          echo "IMAGE_TAG=${VERSION}" >> $GITHUB_OUTPUT

      - name: Login to private Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.mpanin.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.mpanin.me/${{ github.repository }}:${{ steps.version.outputs.IMAGE_TAG }}
            docker.mpanin.me/${{ github.repository }}:latest

      - name: Output image tag
        run: echo "IMAGE_TAG=${{ steps.version.outputs.IMAGE_TAG }}" >> $GITHUB_OUTPUT